FROM java:8
ARG PACKAGE_VERSION
COPY /target/${APPLICATION_NAME}-${PACKAGE_VERSION}.jar ${APPLICATION_NAME}-${PACKAGE_VERSION}.jar
EXPOSE 8080
CMD java -jar ${APPLICATION_NAME}-${PACKAGE_VERSION}.jar
