FROM java:8
ARG PACKAGE_VERSION
ARG APPLICATION_NAME
COPY /target/${APPLICATION_NAME}-${PACKAGE_VERSION}.jar ${APPLICATION_NAME}-${PACKAGE_VERSION}.jar
EXPOSE 8080
CMD java -jar API-javaSpringboot-0.1.0-SNAPSHOT.jar
